image: maven:latest
stages:
    - build
    - test
build:
  image: docker:latest
  stage : build
  services:
    - docker:dind
  script:
    - docker-compose up -d
test:
  stage : test
  script:
    - mvn verify
    - cat target/site/jacoco/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/'
  coverage: '/Total.*?([0-9]{1,3})%/'