version: "3"
services:
  app:
    image: 'demo:latest'
    build:
      context: .
    environment:
      DATASOURCE_USER_JDBCURL: jdbc:postgresql://localhost:5432/postgres
    ports:
      - 8090:8090
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      # - "./data:/var/lib/postgresql"
      - "./data/export.sql:/docker-entrypoint-initdb.d/export.sql"
    ports:
      - "5432:5432"
